### ISSUE TITLE
WjCryptLib_Aes.c run error

### ISSUE THREAD

**Issue by binbinErices** [WaterJuice/CryptLib#2]
**Firstly: WjCryptLib_Aes.c   line 807 "rk -= 3; rrk -= 3;" should be "rk+=3;rrk-=3"
Secondly:when I run the Aes.c Aes.h and Aesblocks,the result is not  same**
`
C:\Users\tianheguoyun\Desktop\temp\build-untitled-Desktop_Qt_5_6_3_MinGW_32bit-Debug\debug>untitled.exe -d 31333530373336333235303133353037 b657a40c5f87fb28ca83e5cd745eefc9
c16a6767fdfdc6e94b6b7118a97759ae

C:\Users\tianheguoyun\Desktop\temp\build-untitled-Desktop_Qt_5_6_3_MinGW_32bit-Debug\debug>untitled.exe -d 31333530373336333235303133353037 b657a40c5f87fb28ca83e5cd745eefc9
109ec21650f21d6f98369528af40ee16

C:\Users\tianheguoyun\Desktop\temp\build-untitled-Desktop_Qt_5_6_3_MinGW_32bit-Debug\debug>untitled.exe -d 31333530373336333235303133353037 b657a40c5f87fb28ca83e5cd745eefc9
90731999c61709d65c9c02d61349e957

C:\Users\tianheguoyun\Desktop\temp\build-untitled-Desktop_Qt_5_6_3_MinGW_32bit-Debug\debug>untitled.exe -d 31333530373336333235303133353037 b657a40c5f87fb28ca83e5cd745eefc9
75f50e479ddae51a329ba9da55210159

C:\Users\tianheguoyun\Desktop\temp\build-untitled-Desktop_Qt_5_6_3_MinGW_32bit-Debug\debug>untitled.exe -d 31333530373336333235303133353037 b657a40c5f87fb28ca83e5cd745eefc9
7965d684ab3ee49697bb7006701fc93c

C:\Users\tianheguoyun\Desktop\temp\build-untitled-Desktop_Qt_5_6_3_MinGW_32bit-Debug\debug>untitled.exe -d 31333530373336333235303133353037 b657a40c5f87fb28ca83e5cd745eefc9
04d93eec6c290a8694f6afd6e000f43c

C:\Users\tianheguoyun\Desktop\temp\build-untitled-Desktop_Qt_5_6_3_MinGW_32bit-Debug\debug>**untitled.exe -d 31333530373336333235303133353037 b657a40c5f87fb28ca83e5cd745eefc9
c67ef2fdff6ce041956206b15d4c3131**

C:\Users\tianheguoyun\Desktop\temp\build-untitled-Desktop_Qt_5_6_3_MinGW_32bit-Debug\debug>**untitled.exe -d 31333530373336333235303133353037 b657a40c5f87fb28ca83e5cd745eefc9
43f0d7fc2011590770913ea69f9d59b1**

C:\Users\tianheguoyun\Desktop\temp\build-untitled-Desktop_Qt_5_6_3_MinGW_32bit-Debug\debug>**untitled.exe -d 31333530373336333235303133353037 b657a40c5f87fb28ca83e5cd745eefc9
3c6c56e8d0700cc5b0cbd5f5cc51ec86**

C:\Users\tianheguoyun\Desktop\temp\build-untitled-Desktop_Qt_5_6_3_MinGW_32bit-Debug\debug>untitled.exe -d 31333530373336333235303133353037 b657a40c5f87fb28ca83e5cd745eefc9
892e8664d2d49952e812fe3cb59e6051

C:\Users\tianheguoyun\Desktop\temp\build-untitled-Desktop_Qt_5_6_3_MinGW_32bit-Debug\debug>`

**I hope author can take free time to help answer my question。thank you！**

**Comment by WaterJuice** [comment]
I do not know why you said that the line at 807 should be changed from rk-=3 to rk+=3.
That is just wrong and 100% the cause of you subsequent strange results. If you change that line to rk+=3 then rk will be pointing out of bounds and into other random parts of memory. Which is why you keep getting a different result each time.

If you leave the line as it was you'll find you'll get the correct result:

```
AesBlock -d 31333530373336333235303133353037 b657a40c5f87fb28ca83e5cd745eefc9

Result: 74616e77656e78756574616e77656e78
```

You can verify this result against openssl using the commands

```
echo 'b657a40c5f87fb28ca83e5cd745eefc9' | xxd -r -p | openssl enc -aes-128-ecb -d -nopad -K 31333530373336333235303133353037 | xxd -p

Result: 74616e77656e78756574616e77656e78
```

**Comment by binbinErices** [comment]
Thanks for author anwser my question. It's my fault，as a beginner, I make a mistake. now I want to konw `static const uint32_t TE1[256] static const uint32_t TD1[256]`,TE1[256] and TD1[256] array how to  construct? I am spent two days time in aes source code
